fura_infosec/apps/employees/urls.py
from django.urls import path

from .views import index, edit_employee

app_name = 'employees'

urlpatterns = [
	path('employees/', index, name='index'),
	path('employees/<int:employee_id>/edit/', edit_employee, name='edit_employee')
]

fura_infosec/apps/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path


app_name = 'users'

urlpatterns = [
	path(
		'logout/',
		LogoutView.as_view(template_name='users/login.html'),
		name='logout'
	),
	path(
		'login/',
		LoginView.as_view(template_name='users/login.html'),
		name='login'
	),
]

fura_infosec/fura_infosec/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.employees.urls', namespace='employees')),
    path('admin/', admin.site.urls),
    path('auth/', include('apps.users.urls', namespace='users')),
]

fura_infosec/apps/employees/models.py
from django.db import models


YES = 'YES'
NO = 'NO'
SIMPLE_CHOICES = [
	(YES, 'Да'),
	(NO, 'Нет')
]


class Department(models.Model):
	dept_name = models.CharField(max_length=100, verbose_name='Департамент')

	def __str__(self):
		return self.dept_name


class Position(models.Model):
	pos_name = models.CharField(max_length=100, verbose_name='Должность')

	def __str__(self):
		return self.pos_name


class Device(models.Model):
	dev_name = models.CharField(max_length=10, verbose_name='Устройство')
	device_lic = models.CharField(
		max_length=3, choices=SIMPLE_CHOICES,
		default=NO, verbose_name='Лицензия устройства',
	)

	def __str__(self):
		return self.dev_name


class Employee(models.Model):
	firstname = models.CharField(max_length=15, verbose_name='Имя')
	lastname = models.CharField(max_length=30, verbose_name='Фамилия')
	middlename = models.CharField(max_length=30, verbose_name='Отчество')
	email = models.EmailField(unique=True, blank=False, verbose_name='Почта')
	phone = models.PositiveIntegerField(
		unique=True, blank=True, verbose_name='Телефон', null=True
	)
	user_lic = models.CharField(
		max_length=3, choices=SIMPLE_CHOICES,
		default=NO, verbose_name='Лицензия пользователя', blank=True
	)
	status = models.CharField(
		max_length=3, choices=SIMPLE_CHOICES,
		default=NO,	verbose_name='Статус отслеживания', blank=True)
	dossier = models.CharField(
		max_length=3, choices=SIMPLE_CHOICES,
		default=NO, verbose_name='Досье сотрудника', blank=True
	)

	department = models.ForeignKey(
		Department, on_delete=models.DO_NOTHING, related_name='department', blank=True, null=True
	)
	position = models.ForeignKey(
		Position, on_delete=models.DO_NOTHING, related_name='position', blank=True, null=True
	)
	device = models.OneToOneField(
		Device, on_delete=models.DO_NOTHING, related_name='device', blank=True, null=True
	)

	def __str__(self):
		return f'{self.lastname} {self.firstname}'

fura_infosec/apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    username = models.CharField(max_length=20, verbose_name='Username')
    email = models.EmailField(verbose_name='Email', unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

fura_infosec/apps/employees/forms.py
from django import forms

from .models import Employee


class QuickEmployeeForm(forms.ModelForm):

	class Meta:
		model = Employee
		fields = ['lastname', 'firstname', 'middlename', 'email']
		labels = {
			'lastname': 'Фамилия',
			'firstname': 'Имя',
			'middlename': 'Отчество',
			'email': 'Адрес корпоративной почты',
		}


class EmployeeForm(forms.ModelForm):

	class Meta:
		model = Employee
		fields = "__all__"
		# exclude = ('status',)
		labels = {
			'lastname': 'Фамилия',
			'firstname': 'Имя',
			'middlename': 'Отчество',
			'email': 'Адрес корпоративной почты',
			'phone': 'Номер корпоративного телефона',
			'department': 'Департамент',
			'position': 'Должность',
			'device': 'Устройство',
			'user_lic': 'Лицензия пользователя',
			'status': 'Статус отслеживания',
			'dossier': 'Досье сотрудника'
		}

fura_infosec/apps/employees/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from .forms import QuickEmployeeForm, EmployeeForm
from .models import Employee


@login_required
def index(request):
	employees = Employee.objects.all()
	quick_create_form = QuickEmployeeForm(request.POST or None)
	if quick_create_form.is_valid():
		employee = quick_create_form.save(commit=False)
		employee.save()
		return redirect('employees:index')
	context = {
		'employees': employees,
		'title': 'FURA IS: Employees',
		'form': quick_create_form
	}
	return render(request, 'employees/nwe_old_index.html', context)


@login_required
def edit_employee(request, employee_id):
	is_edit = True
	employee = get_object_or_404(Employee, pk=employee_id)
	employees = Employee.objects.all()
	form = EmployeeForm(request.POST or None, instance=employee)
	if form.is_valid():
		form.save()
		return redirect('employees:index')
	context = {
		'employee': employee,
		'employees': employees,
		'form': form,
		'is_edit': is_edit,
		'employee_id': employee_id,
		'title': 'FURA IS: Edit employee',
	}
	return render(request, 'employees/nwe_old_index.html', context)

fura_infosec/apps/users/views.py
from django.shortcuts import render

# Create your views here.

fura_infosec/templates/base.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
{% block head %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{{ title }}</title>
  </head>
{% endblock %}
{% block body %}
  <body class="bg-dark">
{% endblock %}

  <div class="container">
    <div class="row align-items-start">
      <div class="col-3">

      </div>
      <div class="col-6">
        {% block main %}
        {% endblock %}
      </div>
      <div class="col-3">
        <div class="flex-shrink-0 p-3 bg-white w-auto">
          {% block search %}
          {% endblock %}
        </div>
      </div>
    </div>
  </div>

</body>

fura_infosec/templates/employees/index.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <title>{{ title }}</title>
</head>
<body>

  <header class="p-3 text-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
          <li><a href="#" class="nav-link px-2 text-dark">Features</a></li>
          <li><a href="#" class="nav-link px-2 text-dark">Pricing</a></li>
          <li><a href="#" class="nav-link px-2 text-dark">FAQs</a></li>
          <li><a href="#" class="nav-link px-2 text-dark">About</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
          <a href="{{ 'users:login' }}">
            <button type="button" class="btn btn-outline me-2">Login</button>
          </a>

          <button type="button" class="btn btn-warning">Sign-up</button>
        </div>
      </div>
    </div>
  </header>

  <main>
    <div class="d-flex flex-column flex-shrink-0 p-3 text-white" style="width: 280px;">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
        <span class="fs-4">Sidebar</span>
      </a>
      <hr>
      <ul class="nav nav-pills flex-column">
        <li class="nav-item">
          <a href="#" class="nav-link active" aria-current="page">
            <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
            Home
          </a>
        </li>
        <li>
          <a href="#" class="nav-link text-dark">
            <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
            Dashboard
          </a>
        </li>
        <li>
          <a href="#" class="nav-link text-dark">
            <svg class="bi me-2" width="16" height="16"><use xlink:href="#table"></use></svg>
            Orders
          </a>
        </li>
        <li>
          <a href="#" class="nav-link text-dark">
            <svg class="bi me-2" width="16" height="16"><use xlink:href="#grid"></use></svg>
            Products
          </a>
        </li>
        <li>
          <a href="#" class="nav-link text-dark">
            <svg class="bi me-2" width="16" height="16"><use xlink:href="#people-circle"></use></svg>
            Customers
          </a>
        </li>
      </ul>
      <hr>
      <div class="dropdown">
        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
          <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
          <strong>mdo</strong>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
          <li><a class="dropdown-item" href="#">New project...</a></li>
          <li><a class="dropdown-item" href="#">Settings</a></li>
          <li><a class="dropdown-item" href="#">Profile</a></li>
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item" href="#">Sign out</a></li>
        </ul>
      </div>
    </div>
  </main>

  <footer class="fixed-bottom p-3 text-dark-50 text-center">
    <div class="container">
      <p class="mt-3">Создано специально для
        <a href="https://fura.com/" class="text-dark">ФУРА</a>, by
        <a href="https://github.com/yumeko6" class="text-dark">Витёк</a>.
      </p>
    </div>
  </footer>

</body>

fura_infosec/templates/employees/nwe_old_index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load split_email %}
{% load user_filters %}
<head data-pg-collapsed>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{{ title }}</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/dataTables.bootstrap5.min.css' %}">
  <script rel="script" src="{% static 'js/jquery-3.7.1.min.js' %}"></script>
  <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
  <script rel="script" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/dataTables.bootstrap5.min.js' %}"></script>
</head>
<body>
  <div class="p-3">
    <nav class="bg-light m-1 navbar navbar-expand-lg navbar-light" data-pg-collapsed>
      <div class="container-fluid"> <a class="navbar-brand" href="#">FURA IS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler6"
                aria-controls="" aria-expanded="false" aria-label="Toggle navigation" data-pg-collapsed>
          <span class="navbar-toggler-icon"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbarToggler6" data-pg-collapsed>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="#">Features</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">Documentation</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">Development</a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink7"
               data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">More</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink7">
              <a class="dropdown-item" href="#">About</a>
              <a class="dropdown-item" href="#">FAQ</a>
              <a class="dropdown-item" href="#">Licence</a>
            </div>
          </li>
        </ul>

        <form class="d-flex">
          <a type="button" class="btn btn-warning" href="{% url 'users:logout' %}">Logout</a>
        </form>
      </div>
    </div>
  </nav>
    <div class="p-3 row">
      <div class="col-md-2 col-xxl-2 h-25 bg-light" data-pg-collapsed>
        <h3>Quick access</h3>
        <div class="container">
          <ul class="flex-column mb-auto nav nav-pills text-body">
            <li class="nav-item"><a href="" class="nav-link link-dark">Employees</a>
            </li>
            <li class="nav-item">
              <a href="" class="nav-link link-dark">Devices</a>
            </li>

            <li class="nav-item">
              <a href="" class="nav-link link-dark">Dossiers</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-10">
        <div class="row">
          <h3 class="col-2">Employees list</h3>
          <div class="col-2">

          <button type="button" class="btn btn-success btn-sm mt-1" data-bs-toggle="modal" data-bs-target="#Modal">
            Quick create
          </button>
            <div class="modal fade" id="Modal" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h1 class="modal-title fs-5" id="ModalLabel">Quick create employee</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <form class="px-4 py-3" method="post" {% if action_url %} action="{% url action_url %}" {% endif %} aria-label="qwe">
                      {% csrf_token %}
                      <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                      <div class="form-group row text-center">
                        <label for="{{ form.lastname.id_for_label }}" class="form-label text-dark">Фамилия</label>
                        {{ form.lastname|addclass:'form-control' }}
                        <label for="{{ form.firstname.id_for_label }}" class="form-label text-dark">Имя</label>
                        {{ form.firstname|addclass:'form-control' }}
                        <label for="{{ form.middlename.id_for_label }}" class="form-label text-dark">Отчество</label>
                        {{ form.middlename|addclass:'form-control' }}
                        <label for="{{ form.email.id_for_label }}" class="form-label text-dark">Почта</label>
                        {{ form.email|addclass:'form-control' }}
                      </div>
                      <div class="modal-footer" align="center">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
          <table class="table" id="sortTable">
            <thead data-pg-collapsed class="text-center">
              <tr data-pg-collapsed>
                <th scope="col">ID</th>
                <th scope="col">Фамилия</th>
                <th scope="col">Имя</th>
                <th scope="col">Отчество</th>
                <th scope="col">Пользователь</th>
                <th scope="col">Телефон</th>
                <th scope="col">Департамент</th>
                <th scope="col">Должность</th>
                <th scope="col">Устройство</th>
                <th scope="col">ЛК</th>
                <th scope="col">ЛП</th>
                <th scope="col">Статус</th>
                <th scope="col">Досье</th>
                <th scope="col">Управление</th>
              </tr>
            </thead>

            <tbody data-pg-collapsed class="fs-6 fw-normal lh-1 text-left">
              {% for emp in employees %}

              <tr data-pg-collapsed data-index="0">
                  <th style="height: 30px;" scope="row">{{ emp.id }}</th>
                  <td style="height: 30px;">{{ emp.lastname }}</td>
                  <td style="height: 30px;">{{ emp.firstname }}</td>
                  <td style="height: 30px;">{{ emp.middlename }}</td>
                  <td style="height: 30px;">{{ emp.email | split_email }}</td>
                  <td style="height: 30px;">{{ emp.phone }}</td>
                  <td style="height: 30px;">{{ emp.department }}</td>
                  <td style="height: 30px;">{{ emp.position }}</td>
                  <td style="height: 30px;">{{ emp.device }}</td>
                  <td style="height: 30px;" class="text-center">
                    {% if emp.device.get_device_lic_display == 'Да' %}
                    <span class="position-absolute translate-middle p-2 mt-2 bg-success border border-light rounded-circle">
                      <span class="visually-hidden">Да</span>
                    </span>
                    {% else %}
                    <span class="position-absolute translate-middle p-2 mt-2 bg-danger border border-light rounded-circle">
                     <span class="visually-hidden">Нет</span>
                    </span>
                    {% endif %}
                  </td>
                  <td class="text-center" style="height: 30px;">
                    {% if emp.get_user_lic_display == 'Да' %}
                    <span class="position-absolute translate-middle p-2 mt-2 bg-success border border-light rounded-circle">
                      <span class="visually-hidden">Да</span>
                    </span>
                    {% else %}
                    <span class="position-absolute translate-middle p-2 mt-2 bg-danger border border-light rounded-circle">
                      <span class="visually-hidden">Нет</span>
                    </span>
                    {% endif %}
                  </td>
                  <td class="text-center" style="height: 30px;">
                    {% if emp.device.get_device_lic_display == 'Да' and emp.get_user_lic_display == 'Да' %}
                    <span class="position-absolute translate-middle p-2 mt-2 bg-success border border-light rounded-circle">
                      <span class="visually-hidden">Да</span>
                    </span>
                    {% else %}
                    <span class="position-absolute translate-middle p-2 mt-2 bg-danger border border-light rounded-circle">
                      <span class="visually-hidden">Нет</span>
                    </span>
                    {% endif %}
                  </td>
                  <td class="text-center" style="height: 30px;">
                    {% if emp.get_dossier_display == 'Да' %}
                    <span class="position-absolute translate-middle p-2 mt-2 bg-success border border-light rounded-circle">
                      <span class="visually-hidden">Да</span>
                    </span>
                    {% else %}
                    <span class="position-absolute translate-middle p-2 mt-2 bg-danger border border-light rounded-circle">
                      <span class="visually-hidden">Нет</span>
                    </span>
                    {% endif %}
                  </td>
                  <td class="text-center" style="width: 30px;">
                    <form method="get" action="{% url 'employees:edit_employee' emp.id %}">
                      <button type="submit" class="btn btn-sm btn-outline-secondary mt-2 mr-1"
                      data-bs-toggle="modal" data-bs-target="#EditModal">
                        <img src="{% static 'img/pencil.svg' %}" alt="pencil" align="right">
                      </button>


                        <div class="modal fade" id="EditModal" tabindex="-1" aria-labelledby="EditModalLabel" aria-hidden="true">
                          <div class="modal-dialog">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h1 class="modal-title fs-5" id="EditModalLabel">Quick edit employee</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                              </div>
                              <div class="modal-body">
                                {% if is_edit and emp.id == employee.id %}
                                <form class="px-4 py-3" method="post" {% if action_url %} action="{% url action_url %}" {% endif %}>
                                  {% csrf_token %}
                                  <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                                  <div class="form-group row text-center">
                                    <label for="{{ form.lastname.id_for_label }}" class="form-label text-dark">Фамилия</label>
                                    {{ form.lastname|addclass:'form-control' }}
                                    <label for="{{ form.firstname.id_for_label }}" class="form-label text-dark">Имя</label>
                                    {{ form.firstname|addclass:'form-control' }}
                                    <label for="{{ form.middlename.id_for_label }}" class="form-label text-dark">Отчество</label>
                                    {{ form.middlename|addclass:'form-control' }}
                                    <label for="{{ form.email.id_for_label }}" class="form-label text-dark">Почта</label>
                                    {{ form.email|addclass:'form-control' }}
                                  </div>
                                  <div class="modal-footer" align="center">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    <button type="submit" class="btn btn-primary">Save changes</button>
                                  </div>
                                </form>
                              </div>
                            </div>
                          </div>
                        </div>
                      {% endif %}
                      </form>
                  </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <script>
    $('#sortTable').DataTable();
  </script>
</body>
</html>

fura_infosec/templates/employees/old_index.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <title>{{ title }}</title>
</head>

<body>
  <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
      </a>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="#" class="nav-link px-2 link-secondary">Home</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">Features</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">Pricing</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">FAQs</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">About</a></li>
      </ul>

      <div class="col-md-3 text-end">
        <button type="button" class="btn btn-outline-primary me-2">Login</button>
        <button type="button" class="btn btn-primary">Sign-up</button>
      </div>
    </header>
  <div class="row">

    <div class="col-2 p-3 bg-white">

      <div>
        <a href="/" class="align-items-center mb-3 mb-md-0 me-md-auto text-decoration-none nav nav-pills flex-column mb-auto">
          <span class="fs-4">Типа новый проект</span>
        </a>
        <hr>
        <ul class="nav nav-pills flex-column mb-auto">
          <li class="nav-item">
            <a href="#" class="nav-link" aria-current="page">
              Home
            </a>
          </li>
          <li>
            <a href="#" class="nav-link link-dark">
              Dashboard
            </a>
          </li>
          <li>
            <a href="#" class="nav-link link-dark">
              Orders
            </a>
          </li>
          <li>
            <a href="#" class="nav-link link-dark">
              Products
            </a>
          </li>
          <li>
            <a href="#" class="nav-link link-dark">
              Customers
            </a>
          </li>
        </ul>
        <hr>
      </div>

    </div>

    <div class="col-10">
      <div>
        <table class="table table-hover table-sm">
          <thead>
            <tr>
              <th scope="col">Фамилия</th>
              <th scope="col">Имя</th>
              <th scope="col">Почта</th>
              <th scope="col">Телефон</th>
              <th scope="col">Департамент</th>
              <th scope="col">Должность</th>
              <th scope="col">Устройство</th>
              <th scope="col">Лицензия пользователя</th>
              <th scope="col">Лицензия устройства</th>
              <th scope="col">Статус</th>
              <th scope="col">Досье</th>
            </tr>
          </thead>
          <tbody>
            {% for emp in employees %}
              <tr>
                <td>{{ emp.lastname }}</td>
                <td>{{ emp.firstname }}</td>
                <td>{{ emp.email }}</td>
                <td>{{ emp.phone }}</td>
                <td>{{ emp.department }}</td>
                <td>{{ emp.position }}</td>
                <td>{{ emp.device }}</td>
                <td>{{ emp.user_lic }}</td>
                <td>{{ emp.device__dev_name }}</td>
                <td>{{ emp.status }}</td>
                <td>{{ emp.dossier }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

  </div>

  <footer class="fixed-bottom py-3 mt-auto text-50 text-center">
    <div class="container">
      <p>Создано специально для
        <a href="https://fura.com/">ФУРА</a>, by
        <a href="https://github.com/yumeko6">Витёк</a>.
      </p>
    </div>
  </footer>

</body>

fura_infosec/templates/users/login.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Войти в TeeVeeAcc</title>
  <meta name="theme-color" content="#212529">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>

<body class="text-center bg-dark">

  <main class="form-signin">
    <div class="container center">
    <form
        method="post"
        {% if action_url %}
          action="{% url action_url %}"
        {% endif %}
    >
      {% csrf_token %}
      <h1 class="h3 mb-3 fw-normal text-white">Please sign in</h1>
        <div class="form-floating mb-2">
          <input type="email" name="username" autocomplete="username" maxlength="254" class="form-control" id="id_username">
          <label for="id_username">Email address</label>
        </div>
        <div class="form-floating mb-3">
          <input type="password" name="password" autocomplete="current-password" class="form-control" id="id_password">
          <label for="id_password">Password</label>
        </div>

      <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
  <footer class="fixed-bottom py-3 mt-auto text-white-50 text-center">
    <div class="container">
      <p>Создано специально для
        <a href="https://fura.com/" class="text-white">ФУРА</a>, by
        <a href="https://github.com/yumeko6" class="text-white">Витёк</a>.
      </p>
    </div>
  </footer>
    </form>
      </div>
  </main>
</body>
</html>